---

- name: wait for ssh proxies to be available
  wait_for:
    port: 22
    host: "{{ item.externalFqdn }}"
    search_regex: OpenSSH
    delay: 30
  with_items: "{{ hostvars.values() | list }}"
  when: (item.hostnameIsProxy is defined) and (item.hostnameIsProxy)

- name: copy private key to proxies
  shell: "scp -i {{ ssh_key_path }} {{ ssh_key_path }} {{ item.ansible_user }}@{{ item.externalFqdn }}:~/.ssh/id_rsa"
  with_items: "{{ hostvars.values() | list }}"
  when: (item.hostnameIsProxy is defined) and (item.hostnameIsProxy)

