---
# tasks file for ravello-provision-app
#
- name: create work directory
  file:
    path: "{{ workdir_path }}"
    state: directory
    recurse: yes

- name: Generate ssh keys for env access
  include: "./ssh_env_keygen.yml"

- name: provision application
  include: "./provision-app.yml"

- meta: refresh_inventory

- name: provision application
  include: "./copy_private_key_to_proxies.yml"

