---
# tasks file for ravello-provision-app
#
- name: create work directory
  file:
    path: "{{ workdir_path }}"
    state: directory
    recurse: yes

- name: Generate ssh keys for env access
  include_tasks: "./ssh_env_keygen.yml"

- name: provision application
  include_tasks: "./provision-app-from-bp.yml"
  when: blueprint_id is defined

- name: provision application
  include_tasks: "./provision-app.yml"
  when: blueprint_id is not defined

- meta: refresh_inventory

- name: copy private key to proxy hosts
  include_tasks: "./configure_ssh_access.yml"

