---

- name: publish application and wait for start
  local_action:
    module: ravello_module
    app_name: "{{ application_name }}"
    description: "{{ application_name }}"
    state: present
    blueprint_id: "{{ blueprint_id }}"
    wait_timeout: "{{ wait_timeout }}"
    application_ttl: "{{ env_expire }}"
    cost_bucket: "{{ ravello_cost_bucket }}"
    publish_optimization: "{{ publish_optimization }}"
    region: "{{ publish_region }}"
    cloud: "{{ publish_cloud }}"
  register: app_results
