---
- name: Generate ssh keypair
  shell: 'ssh-keygen -b 2048 -t rsa -f {{ ssh_key_path }} -q -N ""'
  args:
    creates: "{{ ssh_key_path }}"

- name: get local username
  local_action: command whoami
  register: my_login

- name: get local hostname
  local_action: command hostname
  register: my_domain

- name: set login domain as fact
  set_fact:
    my_login_domain: '{{ my_login.stdout_lines.0 }}@{{ my_domain.stdout_lines.0 }}'

- name: set ssh public key as fact and strip login domain
  set_fact:
    env_public_key: "{{ lookup('file', ssh_key_path + '.pub') | regex_replace(' ' + my_login_domain, '') }}"
