---
- name: display variables for create blueprint from application
  debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - application_name
    - blueprint_name
    - blueprint_description

- name: stop application
  local_action:
    module: ravello_app
    app_name: "{{ application_name }}"
    state: stopped
  register: app_stop_results

- debug:
    var: app_stop_results
    verbosity: 1

- name: create blueprint from application
  local_action:
    module: ravello_app
    app_name: "{{ application_name }}"
    blueprint_name: "{{ blueprint_name }}"
    blueprint_description: "{{ 'blueprint created via ansible from ' + application_name }}"
    state: blueprint
  register: bp_create_results

- debug:
    var: bp_create_results
    verbosity: 1
