---
- name: provision app
  hosts: localhost
  tags:
    - provision
  vars:
    - application_name: my.basic.app
  tasks:
    - include_role:
        name: ravello-provision-app

- name: enable repositories and update system
  become: true
  vars:
    - repo_method: activationkey
  vars_files:
    # rhn credentials
    - <path/to/credentials/file>
  tags:
    - repos
  hosts: 
    - bastion.example.com
    - server.example.com
  tasks:
    - include_role: 
        name: set-repositories
    - yum:
        name: "*"
        state: latest

- name: reboot hosts after update
  tags: 
    - reboot
  hosts: 
    - bastion.example.com
    - server.example.com
  tasks:
    - include_role: 
        name: reboot-host

- name: set motd
  become: true
  tags:
    - motd
  hosts:
    - bastion.example.com
    - webserver.example.com
  tasks:
    - copy:
        content: "Welcome to {{ inventory_hostname }}\n"
        dest: /etc/motd
  

