---
- hosts: localhost
  vars:
    bp_name: 'vvaldez-example_bp-v1.0'
  tasks:
      # Create blueprint based on app template
    - local_action:
        module: ravello_app
        # Make sure you update the version number as the name must be unique
        name: "{{ bp_name }}"
        description: 'Example blueprint created by ansible'
        app_template: 'app_template.yml'
        state: design
      register: design_results

    - debug:
        var: design_results
