:scrollbar:
:data-uri:
:toc2:

== Requirements & Instructions on Using the Ansible Ravello Module

:numbered:

== Overview

The purpose of the Ravello Ansible module is to provide a way to interact with Ravello using their SDK.  The goal is to be able to query, build and deploy Ravello applications using Ansible without having to interact with the Ravello UI.

== Requirements

. Install Ansible `http://docs.ansible.com/ansible/intro_installation.html`
. Install the Ravello SDK via **pip**
+
NOTE: For manual setup instructions see `https://github.com/ravello/python-sdk` and for additional documentation see `http://ravello-sdk.readthedocs.io/en/ravello-sdk-1.4/`
+
----
pip install ravello-sdk
----

=== Test Ravello SDK

. Clone the ravello-sdk locally to use the example scripts
+
----
cd <desired_dir>
git clone https://github.com/ravello/python-sdk.git
----
+
. Change to the **examples** directory
+
----
cd python-sdk/examples
----
+
. Set up credentials file for Ravello using your username and password
+
----
./set-creds
Enter username: yourlogin@redhat.com
Enter a Password:
----
+
. Verify saved credentials
+
WARNING: This will display your password in plain text on the terminal
+
----
cat ~/.ravello_login
<username>
<password>
----
+
. Test the script to get all blueprints you have access to
+
----
./bp-get-all
<all blueprints you have access to>
----

=== Test Capture of Ravello Environment Metadata to JSON

. Test the script to get all applications you have access to
+
----
./app-get-all
<all apps you have access to>
----
+
. Test the script to get all metadata for a specific application and write it to a JSON file
+
NOTE: The option **-a** is for a full JSON dump of extended application metadata
+
----
./app-get-data -a <one app name from output in previous step > myapp.json
----

== Using the Ravello Ansible Module

=== Query the Ravello environment

=== Example Application Creation w/Playbooks

=== Save Deployed Application to a Blueprint

=== Delete the Application
