---
# vars file for ravello-provision-app
instances:
  - name: bastion
    hostname: bastion-REPL.rhpds.opentlc.com
    cpus: 4
    ram: 8
    disks:
      - size: 50
      - size: 100
    nics:
      - name: eth0
        ip: 192.168.1.10
        services:
            - protocol: ssh
              port: 22
    public_key: "{{ env_public_key }}"
  - name: webserver
    hostname: webserver-REPL.rhpds.opentlc.com
    cpus: 2
    ram: 2
    disks:
      - size: 50
    nics:
      - name: eth0
        services:
            - protocol: https
              port: 8443
    public_key: "{{ env_public_key }}"
