---
- name: display variables
  debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - unique_name
    - version
    - application_name
    - application_description
    - blueprint_name
    - blueprint_id
    - wait_timeout

- name: test login
  local_action:
    module: ravello_app
    app_name: "{{ application_name }}"
    state: test
  register: test_results

- debug:
    var: test_results
    verbosity: 1
