#vim: set ft=ansible:
---
######################### Set up Subscription Method (File/Satellite/RHN)

- name: Configure Satellite Subscription
  include_tasks: ./satellite-repos.yml
  when: repo_method == "satellite"
  tags:
    - set_repositories

- name: Configure RHN Subscription
  include_tasks: ./rhn-repos.yml
  when: repo_method == "rhn"
  tags:
    - set_repositories

- name: Configure Repository File
  include_tasks: ./file-repos.yml
  when: repo_method == "file"
  tags:
    - set_repositories

- name: Configure Repository File
  include_tasks: ./activationkey-repos.yml
  when: repo_method == "activation_key"
  tags:
    - set_repositories
