#!/bin/env bash

OUT_FILE=""
THIS_DIR=$(dirname $(readlink -f $0))

while [[ $# -gt 0 ]]; do

case $1 in
  -o)
  OUT_FILE=$2
  shift;shift
  ;;
  *)
  APP_NAME=$1
  shift
  ;; 
esac
done

OUTPUT="#!/bin/env bash

APP_NAME=$APP_NAME

if [[ \$1 == '--list' ]]; then
  python $(realpath $THIS_DIR/../inventory/ravello.py) --list \$APP_NAME
elif [[ \$1 == '--hosts' ]]; then
  python $(realpath $THIS_DIR/../inventory/ravello.py) --hosts
elif [[ \$1 == '--proxy-fqdns' ]]; then
  python $(realpath $THIS_DIR/../inventory/ravello.py) --list \$APP_NAME | \
    gawk 'match(\$0, /proxyFqdn/){print substr(\$2,2,length(\$2)-3)}' | uniq
elif [[ \$1 == '--all-fqdns' ]]; then
  python $(realpath $THIS_DIR/../inventory/ravello.py) --list \$APP_NAME | \
    gawk 'match(\$0, /externalFqdn/){print substr(\$2,2,length(\$2)-3)}' | uniq
fi"

if [[ $OUT_FILE != "" ]]; then
  echo -e "$OUTPUT" > $OUT_FILE
  chmod +x $OUT_FILE
else
  echo -e "$OUTPUT"
fi
  
