#!/bin/env bash

APP_NAME=$1
THIS_DIR=$(dirname $(readlink -f $0))

if [[ "$APP_NAME" != "" ]]; then

mkdir $APP_NAME && \
cat > $APP_NAME/ansible.cfg << END
# ansible.cfg
[defaults]
library      = `readlink -f $THIS_DIR/../library`
roles_path   = `readlink -f $THIS_DIR/../roles`
module_utils = `readlink -f $THIS_DIR/../module_utils`
END

$THIS_DIR/create-inventory `basename $APP_NAME` -o $APP_NAME/inventory

fi

