#!/bin/env bash

APP_PATH=$1
APP_NAME=`basename $1`
THIS_DIR=$(dirname $(readlink -f $0))

if [[ "$APP_PATH" != "" ]]; then

mkdir $APP_PATH && \
cat > $APP_PATH/ansible.cfg << END
# ansible.cfg
[defaults]
library      = `readlink -f $THIS_DIR/../library`
roles_path   = `readlink -f $THIS_DIR/../roles`
module_utils = `readlink -f $THIS_DIR/../module_utils`
END

cat > ${APP_PATH}/${APP_NAME}.yml << END
---
# $APP_NAME.yml

- name: provision my first project
  hosts: localhost
  vars:
   # This variable is used by the ravello-provision-app role
   # to determine the application name
    - application_name: $APP_NAME
  tasks:
   # This role provisions a new application in ravello
    - include_role:
        name: ravello-provision-app
END

mkdir $APP_PATH/host_vars
cat > $APP_PATH/host_vars/localhost.yml << END
---
# host_vars/localhost.yml

instances:
  - name: bastion
    cpus: 1
    ram: 2
END
    

$THIS_DIR/create-inventory $APP_NAME -o $APP_PATH/inventory

fi

