= Tutorial02 - Basic Deployment Configuration

== Prerequisites

- Familiarity with material in previous tutorial

== Initial Setup

This tutorial covers how to set up virtual machine hardware configuration
and how to give ansible access to a deployed application. Since VM definitions 
can become rather verbose, they will end up being placed in a separate file.

To keep deployment projects isolated from one another, we will use a more 
organized approach than in Tutorial01.  We will create a new directory
for the new project.  Since we will no longer be executing playbooks in the 
top-level directory of the repo, we will need to create an `ansible.cfg`
file to tell Ansible where to find our libraries, modules, and utilities.
This repo provides a script to create a project directory as described above,
which is located at `tools/create-project`.

Execute the following command to initialize a blank project directory containing
an `ansible.cfg` file and a dynamic inventory:

```
./tools/create-project my.project.app
```
```
cd my.project.app/
```

The resulting ansible.cfg file will look like this:

```
# ansible.cfg
[defaults]
library      = <path/to>/ansible-ravello/library
roles_path   = <path/to>/ansible-ravello/roles
module_utils = <path/to>/ansible-ravello/module_utils

```

== Create the Provisioning Play

Create a playbook in the new project directory as you did 
in the previous tutorial, replacing the old application name
with the name of the new project.  Additionally, define VM
instances in `host_vars/localhost.yml`, which we will create next.


```
---
# my-project-app.yml

- name: provision my first project
  hosts: localhost
  vars:
   # This variable is used by the ravello-provision-app role
   # to determine the application name
    - application_name: my.project.app
  tasks:
   # This role provisions a new application in ravello
    - include_role:
        name: ravello-provision-app
```

== Define the Instances

We will create a bastion VM and two webservers the hostvars file for localhost.

```
mkdir host_vars && touch host_vars/localhost.yml
```

```
# host_vars/localhost.yml

instances:
  - name: bastion
    hostname: bastion.example.com
    cpus: 1
    ram: 2
    disks:
      - size: 50
      - size: 100
    nics:
      - name: eth0
        ip: 192.168.1.10
    services:
        - protocol: ssh
          port: 22

  - name: webserver1
    hostname: webserver1.example.com
    proxy: bastion
    groups: 
      - webservers
    cpus: 2
    ram: 4
    disks:
      - size: 50
    nics:
      - name: eth0
        ip: 192.168.10.11
    services:
        - protocol: http
          port: 80

  - name: webserver2
    hostname: webserver2.example.com
    proxy: bastion
    groups: 
      - webservers 
    cpus: 2
    ram: 4
    disks:
      - size: 50
    nics:
      - name: eth0
        ip: 192.168.10.12
    services:
        - protocol: http
          port: 80
```

== Enable CDN Subscription

Place your CDN credentials in an ansible-vault encrypted file.

```
rhel_subscription_user: <username>
rhel_subscription_password: <password>
```

```
ansible-vault encrypt <path/to/credentials>
```

Add the following the play to `my-project-app.yml`.

```
- name: enable repositories
  become: true
  hosts: 
    - bastion.example.com
    - webserver1.example.com
    - webserver2.example.com
  vars_files:
    # rhn credentials
    - <path/to/credentials/file>
  vars:
    - repos_to_enable:
      - rhel-7-server-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-7-server-extras-rpms
  tasks:
    - include_role: 
        name: set-repositories
```


== Update system software and reboot

Once subscriptions are enabled on the instances, the systems can
be updated and rebooted.  Since we are using bastion as a proxy,
the webservers will need to rebooted first and bastion second.
The `reboot-host` role will take care of booting ssh_proxies
last, and will wait for the instances to be available again.


```
- name: update systems and reboot
  become: true
  hosts: 
    - bastion.example.com
    - webserver1.example.com
    - webserver2.example.com
  tasks:
    - yum:
        name: "*"
        state: latest
    - include_role: 
        name: reboot-host
```

== Install and configure Apache HTTP Server

```
- name: install and configure httpd
  become: true
  hosts: 
    - webserver1.example.com
    - webserver2.example.com
  tasks:
    - yum:
        name: "httpd"
        state: latest
    - service:
        name: httpd
        state: started
        enabled: yes
```

== Completed Playbook

```
---
# my-project-app.yml

- name: provision my first project
  hosts: localhost
  vars:
   # This variable is used by the ravello-provision-app role
   # to determine the application name
    - application_name: my.project.app
  tasks:
   # This role provisions a new application in ravello
    - include_role:
        name: ravello-provision-app


- name: enable repositories
  become: true
  hosts: 
    - bastion.example.com
    - webserver1.example.com
    - webserver2.example.com
  vars_files:
    # rhn credentials
    - <path/to/credentials/file>
  vars:
    - repos_to_enable:
      - rhel-7-server-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-7-server-extras-rpms
  tasks:
    - include_role: 
        name: set-repositories


- name: update systems and reboot
  become: true
  hosts: 
    - bastion.example.com
    - webserver1.example.com
    - webserver2.example.com
  tasks:
    - yum:
        name: "*"
        state: latest
    - include_role: 
        name: reboot-host


- name: install and configure httpd
  become: true
  hosts: 
    - webserver1.example.com
    - webserver2.example.com
  tasks:
    - yum:
        name: "httpd"
        state: latest
    - service:
        name: httpd
        state: started
        enabled: yes
    - copy:
        content: "<p>Hello from {{ inventory_hostname }}!</p>"
        dest: /var/www/html/index.html
        
```

Deploy the app using the following command (or alternatively use a vault password file):

```
ansible-playbook -i inventory my-project-app.yml --ask-vault-pass
```

== Accessing the Deployed Application

When the deployment is finished, the webservers should be publicly be resolvable via HTTP.
To obtain the fqdns of all of the instances, execute the following command:

```
./tools/get-app-fqdns my.project.app --all
```
Paste the address of each webserver into a browser and you should see the greeting message.
