= Tutorial02 - Basic Deployment Configuration

== Prerequisites

- Familiarity with material in previous tutorial

== Initial Setup

This tutorial covers how to set up virtual machine hardware configuration
and how to give ansible access to a deployed application. Since VM definitions 
can become rather verbose, they will end up being placed in a separate file.

To keep deployment projects isolated from one another, we will use a more 
organized approach than in Tutorial01.  We will create a new directory
for the new project.  Since we will no longer be executing playbooks in the 
top-level directory of the repo, we will need to create an `ansible.cfg`
file to tell Ansible where to find our libraries, modules, and utilities.
This repo provides a script to create a project directory as described above,
which is located at `tools/create-project`.

Execute the following command to initialize a blank project directory containing
an `ansible.cfg` file and a dynamic inventory:

```
./tools/create-project my.project.app

cd my.project.app/
```



The resulting ansible.cfg file will look like this:

```
# ansible.cfg
[defaults]
library      = <path/to>/ansible-ravello/library
roles_path   = <path/to>/ansible-ravello/roles
module_utils = <path/to>/ansible-ravello/module_utils

```

== Create the Project Playbook

Create a playbook in the new project directory as you did 
in the previous tutorial, replacing the old application name
with the name of the new project.  Additionally, include the 
vars file `instances.yml`, which we will create next.


```
---
# my-project-app.yml

- name: provision my first project
  hosts: localhost
  vars:
   # This variable is used by the ravello-provision-app role
   # to determine the application name
    - application_name: my.project.app
  vars_files:
    - instances.yml
  tasks:
   # This role provisions a new application in ravello
    - include_role:
        name: ravello-provision-app
```


